title: Dev Logs
description: My collection of logs pertaining to learning and code.
author: Harry Fahringer
github: https://github.com/harryrf3
about: My collection of logs pertaining to learning and code.
disqus_shortname: devlogs
google_analytics: UA-222285238-2

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#  link: "#"
  - icon: fa-twitter
    link: "https://twitter.com/harryrf3"
#    - icon: fa-linkedin
#      link: "#"
#    - icon: fa-stack-exchange
#      link: "#"
  - icon: fa-github
    link: "https://github.com/harryrf3"

share:
  twitter_username: harryrf3
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
#    To be later reinstated...
#    - text: My Projects
#      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://harryrf3.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

theme: jekyll-theme-cayman